import { up } from "up-fetch";
import z from "zod";
import { $env } from "../env";

export const minifluxSchemas = {
  category: z.object({
    title: z.string(),
    user_id: z.number(),
    id: z.number(),
    hide_globally: z.boolean(),
    feed_count: z.number(),
    total_unread: z.number(),
  }),
  entries: z.object({
    total: z.number(),
    entries: z.array(
      z.object({
        id: z.number(),
        user_id: z.number(),
        feed_id: z.number(),
        title: z.string(),
        url: z.string(),
        comments_url: z.string(),
        author: z.string(),
        content: z.string(),
        hash: z.string(),
        published_at: z.string(),
        created_at: z.string(),
        status: z.string(),
        share_code: z.string(),
        starred: z.boolean(),
        reading_time: z.number(),
        feed: z.object({
          id: z.number(),
          user_id: z.number(),
          title: z.string(),
          site_url: z.string(),
          feed_url: z.string(),
          checked_at: z.string(),
          etag_header: z.string(),
          last_modified_header: z.string(),
          parsing_error_message: z.string(),
          parsing_error_count: z.number(),
          scraper_rules: z.string(),
          rewrite_rules: z.string(),
          crawler: z.boolean(),
          blocklist_rules: z.string(),
          keeplist_rules: z.string(),
          user_agent: z.string(),
          username: z.string(),
          password: z.string(),
          disabled: z.boolean(),
          ignore_http_cache: z.boolean(),
          fetch_via_proxy: z.boolean(),
          category: z.object({
            id: z.number(),
            user_id: z.number(),
            title: z.string(),
          }),
          icon: z.object({
            feed_id: z.number(),
            icon_id: z.number(),
          }),
        }),
      }),
    ),
  }),
  entry: z.object({
    id: z.number(),
    user_id: z.number(),
    feed_id: z.number(),
    title: z.string(),
    url: z.string(),
    comments_url: z.string(),
    author: z.string(),
    content: z.string(),
    hash: z.string(),
    published_at: z.string(),
    created_at: z.string(),
    status: z.string(),
    share_code: z.string(),
    starred: z.boolean(),
    reading_time: z.number(),
    enclosures: z.any(),
    feed: z.object({
      id: z.number(),
      user_id: z.number(),
      title: z.string(),
      site_url: z.string(),
      feed_url: z.string(),
      checked_at: z.string(),
      etag_header: z.string(),
      last_modified_header: z.string(),
      parsing_error_message: z.string(),
      parsing_error_count: z.number(),
      scraper_rules: z.string(),
      rewrite_rules: z.string(),
      crawler: z.boolean(),
      blocklist_rules: z.string(),
      keeplist_rules: z.string(),
      user_agent: z.string(),
      username: z.string(),
      password: z.string(),
      disabled: z.boolean(),
      ignore_http_cache: z.boolean(),
      fetch_via_proxy: z.boolean(),
      category: z.object({
        id: z.number(),
        user_id: z.number(),
        title: z.string(),
      }),
      icon: z.object({
        feed_id: z.number(),
        icon_id: z.number(),
      }),
    }),
  }),
};

export function createMinifluxClient() {
  return {
    request: up(fetch, () => ({
      baseUrl: $env.MINIFLUX_API_URL,
      headers: {
        "content-type": "application/json",
        "x-auth-token": $env.MINIFLUX_API_KEY,
      },
    })),
    schemas: minifluxSchemas,
  };
}
